#!/usr/bin/env bash
# Prepares .env for local development.
#
# Generates SESSION_SECRET on YOUR machine (it never leaves it) and points
# MONGO_URI/REDIS_URL at localhost, because apps/api and apps/worker run on
# the host during development. Inside docker compose those two are
# overridden to the service names, so the same .env works either way.
#
# Plaid credentials are left as REPLACE_ME: the app boots and everything
# except the Plaid calls works without them.
set -euo pipefail

cd "$(dirname "$0")" 2>/dev/null || true
if [ ! -f pnpm-workspace.yaml ] && [ -d "$HOME/Projects/ai-financial-os" ]; then
  cd "$HOME/Projects/ai-financial-os"
fi

if [ ! -f pnpm-workspace.yaml ]; then
  echo "Run this from inside ai-financial-os." >&2
  exit 1
fi

# Preserve anything already set, so re-running never wipes real credentials.
existing() {
  [ -f .env ] || return 0
  grep -E "^$1=" .env 2>/dev/null | tail -1 | cut -d= -f2- || true
}

PLAID_CLIENT_ID_VAL="$(existing PLAID_CLIENT_ID)"
PLAID_SECRET_VAL="$(existing PLAID_SECRET)"
OPENAI_KEY_VAL="$(existing OPENAI_API_KEY)"
SESSION_SECRET_VAL="$(existing SESSION_SECRET)"

if [ -f .env ]; then
  cp .env ".env.backup.$(date +%Y%m%d%H%M%S)"
  echo "Backed up your existing .env"
fi

# 48 random bytes, base64 -- comfortably over the 32-char minimum env.ts enforces.
if [ -z "$SESSION_SECRET_VAL" ] || [ "${#SESSION_SECRET_VAL}" -lt 32 ]; then
  SESSION_SECRET_VAL="$(openssl rand -base64 48 | tr -d '\n')"
  echo "Generated a new SESSION_SECRET"
else
  echo "Kept your existing SESSION_SECRET"
fi

cat > .env <<EOF
# Local development. Generated by dev-setup.sh -- safe to regenerate.
# Never commit this file (.gitignore already excludes it).

NODE_ENV=development
BASE_CURRENCY=USD
PORT=3000

# Generated locally by openssl; rotating it just logs everyone out.
SESSION_SECRET=${SESSION_SECRET_VAL}

# localhost, because api/worker run on the host in development.
# docker-compose.yml overrides both to the internal service names.
MONGO_URI=mongodb://localhost:27017/ai-financial-os
REDIS_URL=redis://localhost:6379

# --- Plaid (https://dashboard.plaid.com -> Team Settings -> Keys) ---
# Sandbox keys are free and need no bank connection.
PLAID_CLIENT_ID=${PLAID_CLIENT_ID_VAL:-REPLACE_ME}
PLAID_SECRET=${PLAID_SECRET_VAL:-REPLACE_ME}
PLAID_ENV=sandbox
PLAID_CLIENT_NAME=Personal Financial OS
# Left unset locally: Plaid can't reach a laptop, so no webhooks fire.
# The scheduled poll (ING-8) covers ingestion in the meantime.
PLAID_WEBHOOK_URL=

# --- OpenAI (Tier 3 categorization, CAT-4 -- not needed yet) ---
OPENAI_API_KEY=${OPENAI_KEY_VAL}

# --- Queue tuning ---
PROVIDER_SYNC_CONCURRENCY=2
PROVIDER_SYNC_RATE_MAX=5
PROVIDER_SYNC_RATE_DURATION_MS=1000
# 5 minutes in development so you don't wait 4 hours to watch it fire.
PROVIDER_SYNC_POLL_INTERVAL_MS=300000

# --- Reverse proxy ---
DOMAIN=localhost
EOF

chmod 600 .env
echo
echo ".env written (mode 600)."

if grep -q "REPLACE_ME" .env; then
  echo
  echo "NEXT: add your Plaid sandbox keys to .env before the Plaid stage of"
  echo "      the smoke test. Everything else runs without them."
fi
